mysql:
  service:
    # The name of the service hosting the MySQL database server,
    # can be customized using the 'MYSQL_SERVICE_NAME' env variable to use a different service
    host:     localhost
    # The database to use, can be customized using the 'MYSQL_SERVICE_DATABASE' env variable
    database: identitydb
    port: 3306

spring:
  datasource:
   driver-class-name: com.mysql.cj.jdbc.Driver
   url: jdbc:mysql://localhost:3306/identitydb
   username: root
   password: admin
  # Spring Data JPA configuration
  jpa:
    hibernate:
  # To be updated in real production usage!
     ddl-auto: update
     show-sql: true
     naming:
      physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    properties:
     hibernate:
       dialect: org.hibernate.dialect.MySQL5Dialect
